Repository SAP/abap-file-formats-tools, pull requests merged in 2022-06, with the labels that each got.

#122 Del msg-119
  src/zaff_tools.msag.xml
  src/zcl_aff_writer_json_schema.clas.abap
  src/zcl_aff_writer_json_schema.clas.testclasses.abap
Labels: UIA

#126 Move msg-125
  src/zaff_tools.msag.xml
  src/zcl_aff_writer_json_schema.clas.abap
  src/zcl_aff_writer_json_schema.clas.testclasses.abap
Labels: UIA

#128 Remove msg-105
  src/zaff_tools.msag.xml
  src/zcl_aff_writer.clas.abap
  src/zcl_aff_writer_json_schema.clas.testclasses.abap
  src/zcl_aff_writer_xslt.clas.testclasses.abap
Labels: YI3

#129 Remove message 107
  src/zaff_tools.msag.xml
  src/zcl_aff_abap_doc_parser.clas.abap
  src/zcl_aff_abap_doc_parser.clas.testclasses.abap
Labels: YI3

#130 Remove message 110 and 111
  src/zaff_tools.msag.xml
  src/zcl_aff_abap_doc_parser.clas.abap
  src/zcl_aff_abap_doc_parser.clas.testclasses.abap
  src/zcl_aff_writer_json_schema.clas.testclasses.abap
  src/zcl_aff_writer_xslt.clas.testclasses.abap
Labels: ALX

#131 Move msg-122
  src/zaff_tools.msag.xml
  src/zcl_aff_writer.clas.abap
  src/zcl_aff_writer_json_schema.clas.abap
  src/zcl_aff_writer_json_schema.clas.testclasses.abap
  src/zcl_aff_writer_xslt.clas.abap
  src/zcl_aff_writer_xslt.clas.testclasses.abap
Labels: UIA

#144 Refactor log
  src/z_generate_repo.prog.abap
  src/zcl_aff_abap_doc_parser.clas.abap
  src/zcl_aff_generator.clas.abap
  src/zcl_aff_log.clas.abap
  src/zcl_aff_tools_unit_test_helper.clas.abap
  src/zcl_aff_writer.clas.abap
  src/zcl_aff_writer_json_schema.clas.abap
  src/zcl_aff_writer_xslt.clas.abap
  src/zif_aff_log.intf.abap
Labels: YI3
